# Generated by Django 4.2.2 on 2023-07-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brasas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
